version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
        interval: 10s
        timeout: 5s
        retries: 3
  postgres:
    image: postgres:14.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - ${DATABASE_PORT}:5432
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mongodb:
